---
- include: Debian.yml
  when: ansible_os_family == "Debian"
  tags: mongo

- include: RedHat.yml
  when: ansible_os_family == "RedHat"
  tags: mongo

- name: Upload SSL certificate
  copy: >
    src=../../../certs/{{ item }}
    dest=/etc/ssl/{{ item }}
    mode=0644
  with_items:
    - {{ certfile }}
    - {{ keyfile }}
  notify:
    - Restart mongodb service
  tags: mongo

- name: Handle mongodb SSL configuration
  lineinfile: >
    dest=/etc/mongodb.conf
    regexp={{ item.regexp }}
    line={{ item.line }}
    state=present
  with_items:
    - { regexp: "^sslOnNormalPorts", line: "sslOnNormalPorts = true" }
    - { regexp: "^sslPEMKeyFile", line: "sslPEMKeyFile = /etc/ssl/{{ keyfile }}" }
  notify:
    - Restart mongodb service
  tags: mongo
