---
- hosts: hublin-slave-local
  connection: local
  vars_files:
    - config.yml
  roles:
    - node
    - hublin

- hosts: hublin-slave
  vars_files:
    - config.yml
  roles:
    - node
    - hublin
